FROM nginx:1.19

ARG COMPOSITION

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/nginx.conf
COPY conf.d /etc/nginx/conf.d

COPY templates/nossl.conf.template /etc/nginx/templates/nossl.conf.template
RUN export COMPOSITION=$COMPOSITION && envsubst '\$COMPOSITION' < /etc/nginx/templates/nossl.conf.template > /etc/nginx/conf.d/nossl.conf
RUN rm -f /etc/nginx/templates/nossl.conf.template
